"""Initial baseline schema.

Creates all current tables (GuildConfig, KBEntry, ConversationMessage, ModLog)
from the SQLModel metadata plus the FTS5 virtual table. Baselining off the model
metadata keeps this migration in lockstep with the models; subsequent schema
changes should be explicit, autogenerated `op.*` migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-14
"""
from typing import Sequence, Union

from sqlmodel import SQLModel

from alembic import op

import bot.database  # noqa: F401 — registers tables on SQLModel.metadata

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_FTS_CREATE = """
CREATE VIRTUAL TABLE IF NOT EXISTS kbentry_fts
USING fts5(title, content, content='kbentry', content_rowid='id')
"""


def upgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.create_all(bind=bind)
    op.execute(_FTS_CREATE)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS kbentry_fts")
    bind = op.get_bind()
    SQLModel.metadata.drop_all(bind=bind)
