"""Pydantic request/response models — the typed API contract."""

from pydantic import BaseModel, Field


class IngestResponse(BaseModel):
    filename: str
    chunks_indexed: int
    message: str


class SearchRequest(BaseModel):
    query: str = Field(..., min_length=1, description="Natural-language question")
    top_k: int | None = Field(
        None, ge=1, le=20, description="Override how many passages to retrieve"
    )


class Source(BaseModel):
    """One retrieved passage backing the answer."""

    index: int = Field(..., description="Citation number referenced as [index]")
    filename: str
    chunk_index: int
    text: str
    score: float = Field(..., description="Cosine similarity (higher = closer)")


class Metrics(BaseModel):
    """Per-query performance instrumentation for the RAG pipeline.

    Latency is broken out by stage so it's clear where time goes (the Claude
    call dominates; local embedding and vector retrieval are sub-second).
    """

    embed_ms: float = Field(..., description="Query embedding time (ms)")
    retrieve_ms: float = Field(..., description="Vector store retrieval time (ms)")
    synthesize_ms: float = Field(..., description="Claude answer synthesis time (ms)")
    total_ms: float = Field(..., description="End-to-end answer_query time (ms)")
    input_tokens: int = Field(..., description="Tokens sent to Claude")
    output_tokens: int = Field(..., description="Tokens generated by Claude")
    estimated_cost_usd: float = Field(
        ..., description="Estimated Claude API cost for this query, in USD"
    )
    top_score: float | None = Field(
        None, description="Cosine similarity of the best-matching passage"
    )


class SearchResponse(BaseModel):
    query: str
    answer: str
    sources: list[Source]
    metrics: Metrics


class DocumentInfo(BaseModel):
    filename: str
    chunks: int


class StatsResponse(BaseModel):
    documents: list[DocumentInfo]
    total_chunks: int
